version: '2'
services:
  fpm:
    build: etc/docker/development/fpm
    environment:
      - SYMFONY_PHPUNIT_VERSION=6.5.0
    volumes:
      - $PWD:/app
    working_dir: /app
    ports:
      - "2222:22"
      - "9000:9000"
